#!/usr/bin/env ansible-playbook
# vim:ft=ansible :

---
- hosts: all
  become: true

  vars_files:
    - defaults/main.yml

  tasks:
    - name: disable selinux on centos
      selinux: state=disabled
      when: ansible_distribution|lower == "centos"

    - name: include main tasks
      include: tasks/main.yml

    - name: restart php-fpm
      service: name=php7.0-fpm state=restarted

    - name: check process
      shell: ps -A | grep php-fpm
      register: php_process

    - name: print process
      debug:
        msg: "{{ php_process.stdout_lines }}"

  handlers:
    - include: handlers/main.yml

